/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LogRouteImport } from './routes/log'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as MethodRouteImport } from './routes/method'
import { Route as PlacesRouteImport } from './routes/places'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ToolsRouteRouteImport } from './routes/tools/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as JournalSlugRouteImport } from './routes/journal/$slug'
import { Route as JourneysIndexRouteImport } from './routes/journeys/index'
import { Route as JourneysSlugRouteImport } from './routes/journeys/$slug'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ToolsConditionsRouteImport } from './routes/tools/conditions'
import { Route as ToolsPackingRouteImport } from './routes/tools/packing'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as JourneysRegionsSlugRouteImport } from './routes/journeys/regions/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesRoute = PlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRouteRoute = ToolsRouteRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysIndexRoute = JourneysIndexRouteImport.update({
  id: '/journeys/',
  path: '/journeys/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysSlugRoute = JourneysSlugRouteImport.update({
  id: '/journeys/$slug',
  path: '/journeys/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsConditionsRoute = ToolsConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ToolsPackingRoute = ToolsPackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => ToolsRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysRegionsSlugRoute = JourneysRegionsSlugRouteImport.update({
  id: '/journeys/regions/$slug',
  path: '/journeys/regions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools': typeof ToolsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRoute
  '/insights': typeof InsightsRoute
  '/log': typeof LogRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/method': typeof MethodRoute
  '/places': typeof PlacesRoute
  '/reviews': typeof ReviewsRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journeys/$slug': typeof JourneysSlugRoute
  '/tools/conditions': typeof ToolsConditionsRoute
  '/tools/packing': typeof ToolsPackingRoute
  '/admin/': typeof AdminIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/journeys/': typeof JourneysIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/journeys/regions/$slug': typeof JourneysRegionsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRoute
  '/insights': typeof InsightsRoute
  '/log': typeof LogRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/method': typeof MethodRoute
  '/places': typeof PlacesRoute
  '/reviews': typeof ReviewsRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journeys/$slug': typeof JourneysSlugRoute
  '/tools/conditions': typeof ToolsConditionsRoute
  '/tools/packing': typeof ToolsPackingRoute
  '/admin': typeof AdminIndexRoute
  '/journal': typeof JournalIndexRoute
  '/journeys': typeof JourneysIndexRoute
  '/studio': typeof StudioIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/journeys/regions/$slug': typeof JourneysRegionsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tools': typeof ToolsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRoute
  '/insights': typeof InsightsRoute
  '/log': typeof LogRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/method': typeof MethodRoute
  '/places': typeof PlacesRoute
  '/reviews': typeof ReviewsRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journeys/$slug': typeof JourneysSlugRoute
  '/tools/conditions': typeof ToolsConditionsRoute
  '/tools/packing': typeof ToolsPackingRoute
  '/admin/': typeof AdminIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/journeys/': typeof JourneysIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/journeys/regions/$slug': typeof JourneysRegionsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tools'
    | '/about'
    | '/gallery'
    | '/insights'
    | '/log'
    | '/login'
    | '/map'
    | '/method'
    | '/places'
    | '/reviews'
    | '/journal/$slug'
    | '/journeys/$slug'
    | '/tools/conditions'
    | '/tools/packing'
    | '/admin/'
    | '/journal/'
    | '/journeys/'
    | '/studio/'
    | '/tools/'
    | '/api/auth/$'
    | '/journeys/regions/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/gallery'
    | '/insights'
    | '/log'
    | '/login'
    | '/map'
    | '/method'
    | '/places'
    | '/reviews'
    | '/journal/$slug'
    | '/journeys/$slug'
    | '/tools/conditions'
    | '/tools/packing'
    | '/admin'
    | '/journal'
    | '/journeys'
    | '/studio'
    | '/tools'
    | '/api/auth/$'
    | '/journeys/regions/$slug'
  id:
    | '__root__'
    | '/'
    | '/tools'
    | '/about'
    | '/gallery'
    | '/insights'
    | '/log'
    | '/login'
    | '/map'
    | '/method'
    | '/places'
    | '/reviews'
    | '/journal/$slug'
    | '/journeys/$slug'
    | '/tools/conditions'
    | '/tools/packing'
    | '/admin/'
    | '/journal/'
    | '/journeys/'
    | '/studio/'
    | '/tools/'
    | '/api/auth/$'
    | '/journeys/regions/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsRouteRoute: typeof ToolsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  GalleryRoute: typeof GalleryRoute
  InsightsRoute: typeof InsightsRoute
  LogRoute: typeof LogRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  MethodRoute: typeof MethodRoute
  PlacesRoute: typeof PlacesRoute
  ReviewsRoute: typeof ReviewsRoute
  JournalSlugRoute: typeof JournalSlugRoute
  JourneysSlugRoute: typeof JourneysSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  JourneysIndexRoute: typeof JourneysIndexRoute
  StudioIndexRoute: typeof StudioIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  JourneysRegionsSlugRoute: typeof JourneysRegionsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places': {
      id: '/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof PlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys/': {
      id: '/journeys/'
      path: '/journeys'
      fullPath: '/journeys/'
      preLoaderRoute: typeof JourneysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys/$slug': {
      id: '/journeys/$slug'
      path: '/journeys/$slug'
      fullPath: '/journeys/$slug'
      preLoaderRoute: typeof JourneysSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/tools/conditions': {
      id: '/tools/conditions'
      path: '/conditions'
      fullPath: '/tools/conditions'
      preLoaderRoute: typeof ToolsConditionsRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/tools/packing': {
      id: '/tools/packing'
      path: '/packing'
      fullPath: '/tools/packing'
      preLoaderRoute: typeof ToolsPackingRouteImport
      parentRoute: typeof ToolsRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys/regions/$slug': {
      id: '/journeys/regions/$slug'
      path: '/journeys/regions/$slug'
      fullPath: '/journeys/regions/$slug'
      preLoaderRoute: typeof JourneysRegionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ToolsRouteRouteChildren {
  ToolsConditionsRoute: typeof ToolsConditionsRoute
  ToolsPackingRoute: typeof ToolsPackingRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteRouteChildren: ToolsRouteRouteChildren = {
  ToolsConditionsRoute: ToolsConditionsRoute,
  ToolsPackingRoute: ToolsPackingRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteRouteWithChildren = ToolsRouteRoute._addFileChildren(
  ToolsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsRouteRoute: ToolsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  GalleryRoute: GalleryRoute,
  InsightsRoute: InsightsRoute,
  LogRoute: LogRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  MethodRoute: MethodRoute,
  PlacesRoute: PlacesRoute,
  ReviewsRoute: ReviewsRoute,
  JournalSlugRoute: JournalSlugRoute,
  JourneysSlugRoute: JourneysSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  JourneysIndexRoute: JourneysIndexRoute,
  StudioIndexRoute: StudioIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  JourneysRegionsSlugRoute: JourneysRegionsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
